export const QUESTS = [
  {
    id: "kill5",
    title: "Clear the Outer Lane",
    desc: "Raider scouts have been harassing ships near the West Relay. Clear out 5 hostile ships so local traffic can move safely again.",
    type: "kills",
    target: 5,
    reward: { credits: 10, scrap: 2 },
    nextQuestID: "scrap10",
  },
  {
    id: "scrap10",
    title: "Recover Field Salvage",
    desc: "The patrol left a debris field around the West Relay. Salvage 10 scrap from the wrecks before the raiders can recover their gear.",
    type: "resource",
    resource: "scrap",
    target: 10,
    reward: { credits: 8, tech: 1 },
    nextQuestID: "admiral1",
  },
  {
    id: "admiral1",
    title: "Break the Raider Command Ship",
    desc: "The scout patrol was only a screen. A hostile admiral has entered the sector near the West Relay to punish the disruption. Destroy the command ship before it regroups the raiders.",
    type: "admiral",
    target: 1,
    reward: { credits: 20, tech: 1 },
    requiresQuestID: "scrap10",
  },
];
