// src/enemyTypes.js
export const enemyTypes = {
  basic: {
    name: "Basic",
    ai: "orbit",
    hp: 24,
    r: 16,
    speedMul: 1.0,
    color: "rgb(170,45,40)",
    fireEnabled: true,
    fireCooldown: 1.2,
    preferredRange: 200,
    spawnWeight: 70,
    gold: 4,
    xp: 100,
  },

  tank: {
    name: "Tank",
    ai: "tank",
    hp: 40,
    r: 22,
    speedMul: 0.65,
    color: "rgb(120,40,40)",
    fireEnabled: true,
    fireCooldown: 2.0,
    preferredRange: 150,
    spawnWeight: 18,
    gold: 9,
    xp: 250,
  },

  sniper: {
    name: "Sniper",
    ai: "sniper",
    hp: 18,
    r: 16,
    speedMul: 0.9,
    color: "rgb(200,200,255)",
    fireEnabled: true,
    fireCooldown: 2.4,
    preferredRange: 420,
    rangeMul: 1.35,
    spawnWeight: 8,
    gold: 7,
    xp: 200,
  },

  disabler: {
    name: "Disabler",
    ai: "kite",
    hp: 28,
    r: 17,
    speedMul: 0.95,
    color: "rgb(140,220,160)",
    fireEnabled: true,
    fireCooldown: 1.7,
    preferredRange: 260,
    appliesSlow: true,
    slowAmount: 0.45,
    slowDuration: 1.6,
    spawnWeight: 4,
    gold: 8,
    xp: 220,
  },
};
